[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[profile.default.model_checker]
extCalls = "trusted"
engine = "chc"
solvers = [ "z3" ]
timeout = 0
targets = [
	"overflow"
]
showProved = true
showUnproved = true
showUnsupported = true
showProvedSafe = true

contracts = { "src/BEC.sol" = ["PausableToken"] }

